### ISSUE TITLE
🐛 [Bug Report] - Swapping Totem-Relics after casting a Damage Spell causes a Global Cooldown to occur

### ISSUE THREAD

**Issue by Hominghead** [Yatzii93/TBC5MAN-Bug-Tracker#10]
# Decription: #
An unknown global cooldown occurs when you cast a damage spell and attempt to equip a different Relic right away.

This does not happen to healing spells however.

# How it works: #

You have Totem of the Thunderhead that increases MP5 provided by Water Shield.
You have Totem of the Storm that increases Lightning Bolt and Chain Lightning damage.

Use 2 Macros:

Macro 1:
/equip Totem of the Storms
/cast Chain Lightning

Macro 2: 
/equip Totem of the Thunderhead
/cast Water Shield

Start with Totem of the Storms equipped.

Cast Macro 1 and attempt to cast Macro 2 right when you end Lightning Bolt cast.

Result: You won't be able to cast Macro 2 for a solid second.

# How to observe: #
Sometimes when you would finish Chain Lightning cast and cast Macro 2, if you right-click equip the Relic in your bag, you can see the skills receiving a global cooldown through equipping.

# How it should work: #
Not entirely sure how retail has it, but i'd imagine that it works the same as the Healing Spells, it shouldn't trigger GCD through equipping a different relic.

# Source - You need to provide a source as evidence: #
Showcase: https://www.youtube.com/watch?v=hmjW5E-pLX4
Healing Spells don't do that: https://www.youtube.com/watch?v=Rn0EvplRauc

# Additional Information: #
👀 srry if it's "working as intended"

**Comment by oldspices** [comment]
Equipping weapons/idols should trigger GCD. you can however "tuck" a weapon swap  gcd inside(after) of a instant cast spell for example  /cast purge /equip idol and you wont suffer from gcd.  you are probably testing heals out of combat as there is no gcd penalty on swapping out of combat...
