### ISSUE TITLE
🐛 [Bug Report] - [Rogue] - Setup talent

### ISSUE THREAD

**Issue by magicganja88** [Yatzii93/TBC5MAN-Bug-Tracker#101]
# Decription: Setup talent does not work. Never gives you combo points when you dodge attack.

# How it works: # No combo points are added when you dodge.

# How it should work: # 45% chance to add combo points to a target when you dodge attack or resist spell.

# Source - https://youtu.be/XrEv9Kw5qNE

# Additional Information: #

**Comment by Yatzii93** [comment]
Previous code only applied if you were actively attacking the target. I've modified it to work even when not.
