### ISSUE TITLE
🐛 [Bug Report] - Priest - Shadowfiend not giving mana back if not in line of sight with priest

### ISSUE THREAD

**Issue by ziokisame** [Yatzii93/TBC5MAN-Bug-Tracker#105]
# Decription: #
Shadowfiend is giving mana back to the priest whenever it hits.

# How it works: #
If the priest cast Shadowfiend on one target and then los the target behind a pillar or whatever obstacle, even if the Shadowfiend hits the target, there is no mana gain.

# How it should work: #
The shadowfiend should always give mana back to the priest, doesn't matter if behind a pillar or not.

# Source - You need to provide a source as evidence: #
https://youtu.be/QyTyNaiEJKs?t=1115
video from hydra filmed on retail. he pops the shadowfiend on the druid then los and still gain mana with one or two hits behind a pillar

# Additional Information: #

**Comment by Yatzii93** [comment]
New round of updates should have fixed this, needs to be retested.

**Comment by ziokisame** [comment]
Unfortunately still not fixed, just tested.

**Comment by Yatzii93** [comment]
Fixed on next restart.
