### ISSUE TITLE
🐛 [Bug Report] - Warrior's Flurry Talent

### ISSUE THREAD

**Issue by zimerek** [Yatzii93/TBC5MAN-Bug-Tracker#11]
# Decription: #
Flurry talent in warrior's Fury tree is bugged.
# How it works: #
After critical strike you get 3 stacks of Flurry, one charge is consumed per autoattack as intended,
but when one charge of Flurry is left and you crit  - buff just dissapears.
# How it should work: #
Like above, but buff should go up to 3 stacks not disappear completely. On 3 stacks and 2 stacks of buff after hitting critcal, buff is refreshed. It only happens when you crit on last charge of Flurry. 
# Source - You need to provide a source as evidence: #
https://wow.gamepedia.com/Flurry_(warrior_ability)

The Burning Crusade Patch 2.4.0 (2008-03-25): Flurry will properly refresh if a crit occurs with 1 charge left.
# Additional Information: #
It seems that it was bug on global too, before patch 2.4.0

**Comment by Yatzii93** [comment]
Dramatime has been looking into this and it seems it could be apart of a larger issue with the proc system. Tbh the whole system needs a overhaul at some point to iron it out. It's similar to the elemental mastery issue. KillerWife from VoA mentioned previously he intends to do the rework. I'll try find some time to have a look as well. But ye sorry about the delay on this one, I always find new things to work on so the bugtracker get less attention that it should.

**Comment by DramatimeWoW** [comment]
I have confirmed this also affects shamans flurry as well.
