### ISSUE TITLE
🐛 [Bug Report] - Interrupting instant spells

### ISSUE THREAD

**Issue by Exeasd** [Yatzii93/TBC5MAN-Bug-Tracker#113]
# Decription: #
Currently you can interrupt instant cast spells for example lifebloom by "getting lucky"
# How it works: #
Whenever you press your interrupt ability at the same time, or close too (my guess is 0.2s delay) when caster press their instant ability you will activly interrupt that spell and lock the caster from that school of magic just like you would interrupt normal cast spell.
# How it should work: #
You should never be able to interrupt instant spells so that mage's who cast blanked 4s cs dont get 8s out of it by just being lucky 
# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by ziokisame** [comment]
I confirm, as disc priest spam dispel, got interrupted multiple times by random feral charges, counterspells etc.

Basically from what i saw if the interrupt lands when your hands are glowing you get full countered.

**Comment by m17a4y** [comment]
I confirm too, it happens if someone uses and interrupt spell while spamming ice lances or arcane explosion and other instant spells.

**Comment by Yatzii93** [comment]
New round of updates may have fixed this, needs replication again.

**Comment by Exeasd** [comment]
Tested it 1 min ago, still not fixed

**Comment by Yatzii93** [comment]
Alright no worries, I thought a public fix would of addressed this, evidently not. I'll code something myself once I've debugged where it's going wrong.
