### ISSUE TITLE
🐛 [Item] - Dragonspine Trophy ppm too high

### ISSUE THREAD

**Issue by Tankdiehutte** [Yatzii93/TBC5MAN-Bug-Tracker#114]
# Decription: Dragonspine Trophy's ppm is too high, leading to a way too high item value. Right now the item is way Stronger than Shard of Contempt and Muru trinket for some classes.

# How it works: Dst's inner cooldown is fine, but the ppm of 1,5 leads to ~50% higher uptime values.
# How it should work: It Should have a 20 seconds inner cd and 1 ppm. Due to abilities that trigger additional hits ( steady shot, whirlwind, crusaderstrike, mortal strike , slam etc. ) the effective ppm settles around 1,5 leading to ~25% uptime (15s / 60s ).

# Source: 
https://de.wowhead.com/item=28830/drachenwirbeltroph%C3%A4e#english-comments
Comment from:  24514, 2007.03.04 (Patch 2.0.8)
"Got this today. Based upon an hour spent in the Blasted Lands, it seems to be somewhere around 1.3 ppm."

 Comment from:  14597, 2007.07.01 (Patch 2.1.2)
About 1.5 PPM for me. (Sword spec Rogue)

https://wowwiki.fandom.com/wiki/Dragonspine_Trophy

"This item has a 20 second hidden cooldown. The proc rate is 1ppm. Uptime averages around 25%."

# Additional Information: #
![WoWScrnShot_102320_204421](https://user-images.githubusercontent.com/56139988/97043747-3801da80-1573-11eb-92e5-624f343dff28.jpg)
Heres a screenshot of the Dsts effective ppm & inner cooldown.

**Comment by Yatzii93** [comment]
Do I have to put you in witness protection for reporting this 0.0 ...

watch your back. I will have a look into this and see if it is infact incorrect.

**Comment by Tankdiehutte** [comment]
![WoWScrnShot_102420_155429](https://user-images.githubusercontent.com/56139988/97083578-3dadfd80-1611-11eb-8240-ef034594b7b7.jpg)
Did another test to prove that its no proccodile bug or sth else. 2,42M Damage. 21 Minutes fightlength. 50 proccs. 2.43 ppm ( tried to do time the whirlwind to match cooldown running out. 40,34% uptime.

**Comment by Tankdiehutte** [comment]
& 20s minimumtime between 2 procs starting

**Comment by Yatzii93** [comment]
![image](https://user-images.githubusercontent.com/47720837/97170417-92718580-1783-11eb-9166-e870fee1e88d.png)

As shown it's already set to 1.5ppmrate and 20seconds internal cd.

**Comment by Tankdiehutte** [comment]
As said. Proccrate is fine. "inner cd too low"

**Comment by Yatzii93** [comment]
Wheres your proof that it has to low an inner cd?

**Comment by Yatzii93** [comment]
Closed until official source can be found. Happy to re-open if this needs to be reinvestigated.

**Comment by Tankdiehutte** [comment]
https://wowwiki.fandom.com/wiki/Dragonspine_Trophy
True its 20s. Found a better source. ppm of 1,5 is too high.
"This item has a 20 second hidden cooldown. The proc rate is 1ppm. Uptime averages around 25%."

**Comment by Yatzii93** [comment]
Changed to 1.0 ppm as shown on wowwiki considering that's properly the best evidence avaiable. Will happily reopen if more official proof is found.

**Comment by kloze1** [comment]
Per the EJ Enhancement Shaman forums, PPM is listed at 1.5:
http://web.archive.org/web/20081013144422/http://elitistjerks.com/f47/t20765-shaman_enhancement/
