### ISSUE TITLE
🐛 [Bug Report] - Priest: Fade not working properly

### ISSUE THREAD

**Issue by ziokisame** [Yatzii93/TBC5MAN-Bug-Tracker#115]
# Decription: #
Fade is a priest spell that allows the priest to drop his threat when the ability is used. The spell is useful only when used in group, if priest gets aggro, when the ability is used the aggro is reduced, and the mobs/boss stop attacking him.
Note that the threat reduction is not permanent, it's temporary for the 10 seconds of the duration of the ability, this means that during fade the priest keeps building threat, and after 10 seconds all the threat that was reduced will be back and added to the new one. 

# How it works: #
Most of the times it does nothing, as you get aggro even if you press it immediately you are still going to get attacked.

# How it should work: #
It should reduce your actual threat 

# Source - You need to provide a source as evidence: #
https://vanilla-wow.fandom.com/wiki/Fade#:~:text=Fade%20is%20a%20temporary%20aggro,they%20heal%20their%20party%20members. Wowiki Fade

# Additional Information: #

**Comment by Yatzii93** [comment]
Im closing this for now considering there isn't any real proof. I've played priest extensively on the core and fade does work. It's saved me many times. Just stating it sometimes doesn't seem to work is not valid enough for a bug report.
