### ISSUE TITLE
🐛 [Potential Security Breach] - Chrome alert on the website

### ISSUE THREAD

**Issue by gbilbao** [Yatzii93/TBC5MAN-Bug-Tracker#117]
# Decription: #
I have a unique combination of name and password which is only used at tbc5man. It seems like it got leaked

# How it works: #
Just visit the homepage

# Source - You need to provide a source as evidence: #
![image](https://user-images.githubusercontent.com/8630284/97782031-7446c380-1b8f-11eb-902f-83940ff18b46.png)

# Change password
How to? I was unable to find information on the page nor in-game. I roughly remember there was some kind of in-game command.

**Comment by Georg-Beischlager** [comment]
This information is provided by google. You get this message when you reuse a password that was part of an earlier leak. Change your password and do not reuse them.

**Comment by Yatzii93** [comment]
No errors from our end. More likely the credentials you used are been farmed somewhere else. Additonally passwords are hashed and encrypted so nobody is able to derive the username or password from the encrypted copy. Also to note, this is for ingame bug tracking not website issues. Please contact a staff member on discord if you have questions.
