### ISSUE TITLE
🐛 [Bug Report] - Hunter - Talent Clever Traps

### ISSUE THREAD

**Issue by Exeasd** [Yatzii93/TBC5MAN-Bug-Tracker#123]
# Decription: #
Duration of the freezing trap in pvp is wrong.
# How it works: #
When you trap someone in pvp using freezing trap, the trap will last 10 sec, even tho you are specced into the clever traps talent.
# How it should work: #
After trapping someone in pvp, he should be trapped for 13s instead of standard 10sec. Thats the only pvp cc spell that last more than 10 sec in the game ( but you need to be specced into said talent.)
# Source - You need to provide a source as evidence: #
https://youtu.be/4jbSgaPROH0?t=45
You can see warrior being trapped at ~46s and comes out of the trap at ~59s
# Additional Information: #

**Comment by Yatzii93** [comment]
- not a bug, comment from july 16th 2007:
" This bull@#$% is finally being nerfed in pvp in patch 2.2, along with an equivalent nerf to Fear, Polymorph, and other CC of the sort.  It will last no more than 10 seconds. " - https://www.wowhead.com/tbc/spell=14311/freezing-trap#comments
