### ISSUE TITLE
🐛 [Bug Report] - Hunter - Snake Trap

### ISSUE THREAD

**Issue by Exeasd** [Yatzii93/TBC5MAN-Bug-Tracker#124]
# Decription: #
Snakes from snake trap have way too much hp.
# How it works: #
Currently snakes have 1.4k hp.
# How it should work: #
Snakes should have less than 86hp
# Source - You need to provide a source as evidence: #
https://youtu.be/9qv4nbt-NNk?t=281
We can see from 4:41 that shaman is placing magma totem to counter snakes. It ticks for 86 and kills all the snakes in range.
# Additional Information: #

**Comment by Yatzii93** [comment]
Will be fixed after next restart.
