### ISSUE TITLE
🐛 [Bug Report] - Voodoo Feather Quest Broken by Ocean Hippogryph Mount

### ISSUE THREAD

**Issue by poggersss** [Yatzii93/TBC5MAN-Bug-Tracker#125]
# Decription: #
Voodoo Feather Quest should require two Blue Voodoo Feather and they should drop from the troll minibosses in Sunken Temple. Appears the blue voodoo feather item was used for Ocean Hippogryph mount, which breaks the quest and makes it impossible to complete as the trolls do not drop this.

# How it works: #

[Voodoo Feathers](https://tbc-twinhead.twinstar.cz/?quest=8425) should require two amber voodoo feathers, two green voodoo feathers, and two blue voodoo feathers. The amber and green feathers are correct, but instead of blue feathers it says it requires two "Ocean Hippogryph." Four of the trolls drop the correct feathers (amber and green). The two minibosses ([Mijan](https://tbc-twinhead.twinstar.cz/?npc=5717) and [Hukku ](https://tbc-twinhead.twinstar.cz/?npc=5715)) that should drop the blue feathers do not. 

Appears that the blue voodoo feather item was used for the Ocean Hippogryph Mount, making the quest impossible to complete.

# How it should work: #

Troll minibosses [Mijan ](https://tbc-twinhead.twinstar.cz/?npc=5717)and [Hukku ](https://tbc-twinhead.twinstar.cz/?npc=5715) in Sunken Temple should drop [Blue Voodoo Feathers](https://tbc-twinhead.twinstar.cz/?item=20607) for the quest [Voodoo Feathers](https://tbc-twinhead.twinstar.cz/?quest=8425).

Would be nice to be able to complete this quest, either via workaround or by reverting the blue feather back.

# Source - You need to provide a source as evidence: #
![image](https://user-images.githubusercontent.com/63026698/100582102-b9593500-32b6-11eb-9272-a4cac6a7ec8d.png)

# Additional Information: #

**Comment by Yatzii93** [comment]
The server is focused on TBC only. There really isn't any reason to revert custom items that break redunant old world quests. The item was chosen for it's icon more so than anything. At this time this is a "won't fix" issue. Thanks for the report though.
