### ISSUE TITLE
🐛 [Bug Report] - Druid - Malorne Rainment (t4) 2 set bonus not working on lifebloom/rejuvenation casts

### ISSUE THREAD

**Issue by Ddenktank** [Yatzii93/TBC5MAN-Bug-Tracker#126]
# Decription: #
Malorne Rainment 2 set bonus reads ‘Your helpful spells have a chance to restore up to 120 mana’.

# How it works: #
The set bonus is currently not working when casting Lifebloom and Rejuvenation. 
After testing I found the proc only oncurring when casting Healing Touch or Regrowth. 

# How it should work: #
As is the description reads it should have a chance to proc on casting all helpful spells, including Lifebloom and Rejuvenation.  
Considering raiding (treeform) druids  use lifebloom and rejuvenation about every global cooldown and alot more than Regrowth and especially Healing Touch, this bug removes much if not nearly all of the value of the set bonus. 

# Source - You need to provide a source as evidence: #
See the following link with comments from retail explicitly mentioning a the proc occuring on casting lifebloom: https://www.wowhead.com/item-set=638/malorne-raiment#comments
Like: 
__By BlackWvyern (1,975 – 9•19) on 2007/09/13 (Patch 2.1.3)
“Did a little testing of my own after getting this, there is no internal cooldown on the proc of the two-piece set bonus, as I was spamming lifeblooms and got it to proc two times in a row, given lifebloom is an instant with the global one second cooldown. As far as percentage goes, I would have to say it's about a 5% chance to go off. I get the 120 mana proc a lot more often than my insightful earthstorm diamond proc, which is 2%, but it is no where close to being once in ten casts, or, 10%.”_
And:_
_“82268 on 2007/09/14 (Patch 2.1.3)
i tested this too. after 250 casts of lifebloom, i got 10 procs on the 2set bonus, which equals exactly 4%. all gains were exactly 120 mana. also, agreed there is no internal cooldown. i actually got 4 procs in a row. i was very surprised.”_

# Additional Information: #
Item set: https://tbcdb.com/?itemset=638 
Set bonus: https://tbcdb.com/?spell=37288#itemsets

**Comment by Yatzii93** [comment]
This should be fixed now I've updated it's spell proc to now be affected by instant healing spells.
