### ISSUE TITLE
🐛 [Bug Report] - Ellrys Duskhallow's Death Coil is a buff instead of a debuff

### ISSUE THREAD

**Issue by Hominghead** [Yatzii93/TBC5MAN-Bug-Tracker#128]
# Decription: # 
In Magister's Terrace Council fight, whenever Ellrys Duskhallow uses Death Coil, the "fear" component is a buff that can be clicked away rather than a debuff

# How it works: # 
Death Coil effect can be right-clicked and get cancelled like any buff

# How it should work: # 
Death Coil should be a debuff

# Source - You need to provide a source as evidence: # 
https://www.youtube.com/watch?v=BKOq7mou94Q

# Additional Information: #
CatJam

**Comment by Hominghead** [comment]
Also affects Olm the Summoner in Gruul's Lair

**Comment by Yatzii93** [comment]
Fixed. Thanks
