### ISSUE TITLE
🐛 [Bug Report] - Attackspeed Normalisation doesnt exist for many Spells

### ISSUE THREAD

**Issue by Tankdiehutte** [Yatzii93/TBC5MAN-Bug-Tracker#139]
Decription: Many instand weapondamage attacks should only get normalised weapondamage bonus from Attackpower, instead of it depending on the weaponspeed of your current weapon, so currently slow weapons ( Glaives, MoM, Twins bow) benefit too hard from their slow weapon speed, getting too much damage from attackpower. E.g. 5k whirwinds in PvP with Might of Menethil in Bgs.

How it works: " Currently it uses the pre patch 1.8, formula sth similar to : "damage = base_weapon_damage + (weapon_speed * Attack Power / 14)" , So glaivewarriors Whirlwind offhand damage is too low and the mainhand damage too high.

How it should work: "Prior to patch 1.8, the weapon damage used for instant attacks was:

damage = base_weapon_damage + (weapon_speed * Attack Power / 14)
Currently, the normalized weapon damage for instant attacks is:

normalized_damage = base_weapon_damage + (X * Attack Power / 14)
where X is:

1.7 for daggers
2.4 for other one-handed weapons
3.3 for two-handed weapons
2.8 for ranged weapons "

Source: https://wowpedia.fandom.com/wiki/Normalization?oldid=1563852 

 Additional Information:  The source is from August 7th, 2008, Missing spells are: Steady shot as Normalised (Also 2.8) and Crusaderstrike as non Normalised ( Gets Normalised in later patches)

**Comment by Yatzii93** [comment]
Lacks any form of evidence. Closing for now
