### ISSUE TITLE
website password bug

### ISSUE THREAD

**Issue by G2G2G2G** [Yatzii93/TBC5MAN-Bug-Tracker#142]
# Decription: #
The website account creation allows unlimited characters both client and server side

# How it works: #
put too many characters in and you cannot login

# How it should work: #
client and server limits the password by 16 characters just like the WoW game login does

# Source - You need to provide a source as evidence: #
You have:
```html
<input class="living-input" name="password" type="text" value="Password" onFocus="this.value=''" />
```
you should have:
```html
<input class="living-input" name="password" type="text" value="Password" maxlength="16" onFocus="this.value=''">
```
Also the onFocus is kind of annoying if you go to edit the password, I assume it is to be a "placeholder" for your "Password" text in your value input? And you wanted to replace it. The proper way is to do this:
```html
<input class="living-input" name="password" type="text" placeholder="Password" maxlength="16">
```
(note the several changes)

# Additional Information: #
The length should also be enforced server side. If someone makes a password longer than 16 characters on the web page they won't be able to login via the game, and there's no password reset option either. 
There are several other errors around the web pages. 

You're very hard to contact, this page isn't readily available anywhere? Can't msg you through discord, can't use your server's discord without verifying a phone etc. By how it looks now I assume it's only a matter of time until someone comes along and finds something they shouldn't and deletes the database or something stupid like molten had happen to them. Is there a place to look over the web server side? (no offense, just bad to have stuff happen)
Thanks

**Comment by Yatzii93** [comment]
I was aware of the issue, it's sorted now the check was to long. However I find it odd that you are just assuming you know the code, you don't. The last thing I need is someone trying to dictate something they have no visability over.

**Comment by G2G2G2G** [comment]
Sloppy people are sloppy all over, not in 1 area
