### ISSUE TITLE
🐛 [Bug Report] - Priest Powerword Shield not working correctly

### ISSUE THREAD

**Issue by Realizer31** [Yatzii93/TBC5MAN-Bug-Tracker#146]
# Decription: #
Powerword Shield should should absorb more from addheal but it does not.

# How it works: #
At the moment it absorbs the exact ammount of damage that in the tooltip.

# How it should work: #
It should absorb 30% additional from your total Bonus Healing.

# Source - You need to provide a source as evidence: #
https://wowpedia.fandom.com/wiki/Power_Word:_Shield?oldid=1431857
(see the notes)
or
https://wowwiki-archive.fandom.com/wiki/Power_Word:_Shield?oldid=1137379
# Additional Information: #

**Comment by Yatzii93** [comment]
I'll have a look shortly.

**Comment by Realizer31** [comment]
I found another issue concerning the Priest Shield, guess its okay to write it here rather to open another topic.
Reflective shield should be able to hit crital but it does not. 
As it reflects holy dmg it should use the Holy spell crit chance.

You can look it up here: "Reflective Shield can crit..."
https://wowpedia.fandom.com/wiki/Reflective_Shield

Here is a video proof of an 14year old tbc video where someone is testing it. You can see it crit several times.
https://www.youtube.com/watch?v=b_WChd_H4x8

**Comment by Yatzii93** [comment]
Tested myself and proven to be working fine. Feel free to comment with your own findings if you believe this to be incorrect.
