### ISSUE TITLE
🐛 [Bug Report] - Priest Talent "Force of Will" not working at all

### ISSUE THREAD

**Issue by Realizer31** [Yatzii93/TBC5MAN-Bug-Tracker#147]
# Decription: #
Talent "Force of Will" not working at all

# How it works: #
It does not increase any spell crit or spell dmg. At least it does not when you look at your character stats.

# How it should work: #
It should increase offensive spell crit and also spell dmg by 1% each talent point

# Source - You need to provide a source as evidence: #
Description of the talent.

# Additional Information: #

**Comment by Yatzii93** [comment]
I'll have a look shortly. Thank you

**Comment by Yatzii93** [comment]
yes sorry, this will be checked shortly.
