### ISSUE TITLE
🐛 [Bug Report] - Gnomish Battle Chicken doesn't stack

### ISSUE THREAD

**Issue by buggiestbugofallbugs** [Yatzii93/TBC5MAN-Bug-Tracker#149]
# Decription: #
Engineering trinket Gnomish Battle Chicken applies a buff "Battle Squawk" and when used by multiple party members it should stack.
# How it works: #
The buff does not stack when used by different party members.
# How it should work: #
The buff should stack.
# Source - You need to provide a source as evidence: #
https://youtu.be/mikR2nzg8A4?t=20
In this clip Ahlaundoh has 5 Battle Squawk buffs on TBC Classic
# Additional Information: #
The item that spawns the chicken: https://tbc.wowhead.com/item=10725/gnomish-battle-chicken
The chicken that does the buff: https://tbc.wowhead.com/npc=8836/battle-chicken#abilities;mode:n10
The buff that is supposed to stack: https://tbc.wowhead.com/spell=23060/battle-squawk

**Comment by Yatzii93** [comment]
Intended on this server
