### ISSUE TITLE
🐛 [Arena chest event] - Manaforge Ultris

### ISSUE THREAD

**Issue by Julzyo** [Yatzii93/TBC5MAN-Bug-Tracker#15]
# Decription: #
Teleport issue with portal from Shattrath.
# How it works: #
Clicked the portal from Shattrath when event started, ended up teleported over the void south of Manaforge Coruu and died, had to take res sickness. 
# How it should work: #
Fix possible TP location.
# Source - You need to provide a source as evidence: #
/ 
# Additional Information: #
/

**Comment by Yatzii93** [comment]
I'll take a look!
