### ISSUE TITLE
🐛 [Bug Report] - Sweeping Strikes does not do the correct damage

### ISSUE THREAD

**Issue by buggiestbugofallbugs** [Yatzii93/TBC5MAN-Bug-Tracker#150]
# Decription: #
Currently Sweeping Strikes does flat damage when its supposed to do whatever the hit that procs it does
# How it works: #
Sweeping strikes causes same damage for any hit, for example a 91 hamstring does 539 sweeping strikes and 1763 bloodthirst does 538 sweepign strikes.
# How it should work: #
Sweeping strikes damage should be based on the damage that procs it, which is how rogue's blade flurry currently works.
# Source - You need to provide a source as evidence: #
Warrior sweeping strikes:
https://classic.warcraftlogs.com/reports/DHCbj41x8PKV9MX2#fight=18&type=damage-done&source=15&view=events

Rogue bladeflurry:
https://classic.warcraftlogs.com/reports/DHCbj41x8PKV9MX2#fight=18&type=damage-done&source=18&view=events

Tidalvess debuffs:
https://classic.warcraftlogs.com/reports/DHCbj41x8PKV9MX2#fight=18&type=auras&hostility=1&source=167&spells=debuffs

Sharkkis debuffs:
https://classic.warcraftlogs.com/reports/DHCbj41x8PKV9MX2#fight=18&hostility=1&source=170&type=auras&spells=debuffs

Pictures for easy viewing:
https://cdn.discordapp.com/attachments/916520321954246659/918001361424105482/unknown.png

# Additional Information: #
As mentioned in the picture link, Blade Flurry is currently ignoring the secondary targets armor, when it shouldnt be.
So all that needs to be done is make Sweeping Strikes same behavior as Blade Flurry but make them NOT ignore the secondary target's armor.

**Comment by Yatzii93** [comment]
Fixed in fresh
