### ISSUE TITLE
🐛 [Bug Report] - Illidan eye beam gains aggro table in the event of a player death

### ISSUE THREAD

**Issue by saasen** [Yatzii93/TBC5MAN-Bug-Tracker#154]
# Description: #

We were fighting Illidan, and it seemed like the eye beam was following us.

# How it works: #

Eye beam following party members.

# How it should work: #

Eye beam not following, it should be in a straight line?

# Source - You need to provide a source as evidence: #

Here's a video showing it:
https://1drv.ms/v/s!AlrA1SIQbKulirMRFrq_T14OK0rl_A?e=3n0D3K

# Additional Information: #

**Comment by Yatzii93** [comment]
Seems the beam gained a aggro table once it hit/killed one of the party members. I can take a look to see.
