### ISSUE TITLE
🐛 [Bug Report] - Emerald Dream issue with Nature Resistance

### ISSUE THREAD

**Issue by OcciputTBC5man** [Yatzii93/TBC5MAN-Bug-Tracker#156]
# Decription: #Currently Nature Resistance items don't provide any help in either resisting or reducing incoming dmg from Noxious Breath (the dot damage from Ysondre

# How it should work: #according to https://de.classic.wowhead.com/npc=14887/ysondre#english-comments nature resistance should help in resisting the dot to begin with

# Source - You need to provide a source as evidence: # https://de.classic.wowhead.com/npc=14887/ysondre#english-comments

![image](https://user-images.githubusercontent.com/108155879/175695442-953745b1-973d-4c78-bdcb-84877886600d.png)

**Comment by Yatzii93** [comment]
intended for the custom fight.
