### ISSUE TITLE
🐛 [Bug Report] - Retribution Paladin Seal Twist

### ISSUE THREAD

**Issue by AntonioPeremin** [Yatzii93/TBC5MAN-Bug-Tracker#169]
# Decription: #Seal Twist

# How it works: #It Doesn't work at all.Seal of Command procs instantly ,not after 0.5 seconds like it should to make the mechanics work.

# How it should work: #When Seal of Command procs there is a 0.5 seconds delay on the proc and you press seal of blood in 0.5seconds delay It should give you 2x extra seal of blood procs.

# Source - You need to provide a source as evidence:https://youtu.be/1ud1KQvvs1M

https://www.reddit.com/r/classicwowtbc/comments/n9pvba/tbc_classic_paladin_detailed_seal_twisting_guide/

# Additional Information: #It is used by Retribution paladins.It increases overall damage by 20-30%.

**Comment by Tankdiehutte** [comment]
Funfact. This is not a bug report. This looks more like a complain about a mechanic not exsisting due to 3-4 bugs.

**Comment by AntonioPeremin** [comment]
> This is not a bug report. This looks more like a complain about a mechanic not exsisting due to 3-4 bugs.

How to explain it more detailed?

**Comment by Yatzii93** [comment]
Seal twisting only existed due to spell batching. If it was introduced here it would be a custom implementation to mimic a bug caused by something that doesn't exist and no one would want to exist on a private server. Doesn't mean it won't ever appear but it's not a bug per say.
