### ISSUE TITLE
[BUG] Quest: Secrets of the Talonpriests / 

### ISSUE THREAD

**Issue by Yesisquat** [Yatzii93/TBC5MAN-Bug-Tracker#19]
Hello,
I am trying to farm reputation for Sha'tari Skyguard.
I recognized the issue when I tried to do the Quest Secrets of the Talonpriest in Skettis/Terrokar Forrests (https://www.wowhead.com/quest=11005/secrets-of-the-talonpriests). In this quest you need to farm Skettis mobs which drops Shadow Dust (https://tbc-twinhead.twinstar.cz/?item=32388). You can trade 6 Shadow Dust for Elixir of Shadow which enables you to see the Shadow World. This is the part which is not working. I consume the Elixir of Shadows, but I am not able to enter the Shadow World and see the mobs & NPC there.
Hope you can help to fix the problem.

**Comment by Yatzii93** [comment]
This works fine.
