### ISSUE TITLE
🐛 [Bug Report] - [ITEM] "Shifting Naaru Sliver"- On use effect bugged

### ISSUE THREAD

**Issue by Redeyed03** [Yatzii93/TBC5MAN-Bug-Tracker#2]
# Decription: # The trinket Shifting Naaru Sliver's on use effect does not work. More specifically, the 320 SP buff circle does not work.

# How it works: # When you click the trinket, it currently displays the correct graphic on the ground but no buff applied.

# How it should work: #When you click the trinket, it should display the graphic on the ground as well as provide a 320 spell power buff while standing in the graphic.

# Source - You need to provide a source as evidence: #https://tbc-twinhead.twinstar.cz/?item=34429

# Additional Information: #

**Comment by Razfi** [comment]
can confirm just got it
