### ISSUE TITLE
[Bug Report] - Sanctified Seals not working proprely.

### ISSUE THREAD

**Issue by kamil87** [Yatzii93/TBC5MAN-Bug-Tracker#24]
Decription: Sanctified Seals 3/3 is not working. Your seals can still be tried to be dispelled. The undispellable part is working versus all class beside mage. They can steal our seals. Other class can still try to dispel you even if you have no buff. 

How it works:
People can still try to dispel you. Mage can steal your seals. 

How it should work:
When you have 3/3 sanctified seals: your seals should be removed from the dispel list and dispeller that try to dispel you when you have no buff active and only your seal should be granted an error message: There's nothing to dispel on this target. Mage spell steals is suppose to act the same, but right now they can even steal our seals. 

Source - You need to provide a source as evidence:
Dispel effects will no longer attempt to remove effects that have 100% dispel resistance.
It is the first line of Patch 2.4.3 here : https://wowwiki.fandom.com/wiki/Patch_2.4.3

Additional Information:
Rank 1 should be 33% resistance for your seals and rank 2 should be 66%. Alot of good ret paladin often go this talent 2/3 with Stoicism so they can get 96% resist on their seals, so it's important that all single point are fixed as well right now it seems that 1/3 and 2/3 have no chance to resist dispel. 
Here are some screenshots I took from some quick testing I've done, specced 2/3 sanctified seals and got 1 resist out of so many spell steal its 66% it should resist at least half the time ... 
https://imgur.com/a/GranCE3

It's pretty easy to reproduce, log in a ret pally with sanctified seals and any dispeller(should pick a mage to see that extra spell steals bug) 

Thanks in advance hopefully this can get resolved pretty quickly.

**Comment by Yatzii93** [comment]
I've reviewed this and as far as I can see this talent is working correctly, seals are not being dispelled when the player has 3 points in the Sanctified Seal talent.
