### ISSUE TITLE
Strange mana regen bug in Underbog

### ISSUE THREAD

**Issue by mecserim** [Yatzii93/TBC5MAN-Bug-Tracker#25]
Not a big issue, but happened to me at least twice in the last days: in the tunnel leading to the 3rd boss (Swamplord), my healer priest's (Lois) combat mana regen drastically drops. Usually it is around 270 mana/5sec in combat, but goes down to 56 mana/5sec. Also my healing power and my heals gets much weaker.

**Comment by Yatzii93** [comment]
I cannot recreate this, plus I can't see how a location could cause such a bug. Could you please take screenshots of your character pane clearly showing the reduction whilst in the location specified.

**Comment by mecserim** [comment]
Hi,

I think too it's not location specific, happened to me in OHF and ramparts,
last time I took screenshots to show you.
Only difference on my char is a new boj wand, no talent change.

Yatzii <notifications@github.com> ezt írta (időpont: 2020. jan. 18., Szo,
21:06):

**Comment by Yatzii93** [comment]
Closing due to lack of information - will reopen if something applicable is submitted.
