### ISSUE TITLE
BLACK TEMPLE - SUPREMUS

### ISSUE THREAD

**Issue by madalis** [Yatzii93/TBC5MAN-Bug-Tracker#27]
so we went in the boss supremus in black temple and in phase 2 we tryied to be in 30-40 yards away from him but he charge none stop and he killed us we tryied to run as far away us we can and the same thing basically we triyed everything and we cant understand how the phase 2 works we believe its bagged and we have exp of black temple this thing never happen if u can help it will be nc

**Comment by Yatzii93** [comment]
Fights working as intended, you must be closer than you think.
