### ISSUE TITLE
🐛 [Bug Report] - AV Debuff Bugged

### ISSUE THREAD

**Issue by Nsnugget** [Yatzii93/TBC5MAN-Bug-Tracker#3]
# Decription: # AV debuffed bugged. Healing reduced too high.

# How it works: # Healing reduced 10% per stack. (says 5%)

# How it should work: # Healing reduced 5% per stack

# Source - You need to provide a source as evidence: # At 10 stacks in AV you no longer are able to be healed.

# Additional Information: #

**Comment by Nsnugget** [comment]
Guess it is intended to change the tooltip as to not confuse healers trying to heal ppl with the stacks.

**Comment by Yatzii93** [comment]
Tooltips cant be changed as they are held in the client software. The increase in healing reduction is intended to minimize snowballing.
