### ISSUE TITLE
🐛 [Bug Report] - [Battlegrounds] [Flags cannot be picked while stealthed/shadowmelded]

### ISSUE THREAD

**Issue by Schmoha** [Yatzii93/TBC5MAN-Bug-Tracker#30]
# Decription: # As a Rogue i cannot pick the flags in EotS, AB and WSG while in Stealth and Shadowmeld.

# How it works: #

# How it should work: # Should work from stealth and shadowmeld.

# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by Yatzii93** [comment]
Please fill out the form properly and provide evidence.
