### ISSUE TITLE
🐛 [Bug Report] - Kael'Thas goes inactive and then locks us out after "kill"

### ISSUE THREAD

**Issue by nevinera** [Yatzii93/TBC5MAN-Bug-Tracker#4]
# Description:
Our group was running Magister's Terrace (on normal mode), and wiped on Kael a second time, but then he never got around to killing the last of our DPS (farnsworth), who proceeded to lightning bolt him to death solo.

* The scripted mechanics did something that may have been strange (it transitioned out of and then later back into floaty mode before he finally died)
* Farnsworth died around the same time as the kill (I think he was inside an arcane sphere?)
* We all released and ran back afterwards, and the door is still covered by the graphics that don't let us through, and his body doesn't appear to be lootable. Also, no credit for the kill on the daily quest.

The only real pain for us was that we didn't get to keep trying him (running the rest of the dungeon took a while); we definitely wouldn't have legitimately beat him on that attempt. But I wanted to report it in case it's helpful for finding whatever caused the actual bug here (which I assume can be encountered in heroic mode too).

# Source - You need to provide a source as evidence:
![Screen Shot 2019-10-05 at 6 56 10 PM](https://user-images.githubusercontent.com/366133/66261847-9e6a5e00-e7a2-11e9-9c5b-2f92a649fcb9.png)

**Comment by nevinera** [comment]
(If you don't have other reports about this issue, feel free to resolve it - debugging a very rarely reported problem like this is probably not worth your time)

**Comment by Yatzii93** [comment]
My recent change should of fixed this concerning the spheres properly despawned on kael end.
