### ISSUE TITLE
[MAGE] Arcane Missiles + Clear Casting🐛 [Bug Report] - 

### ISSUE THREAD

**Issue by Lunacy1992** [Yatzii93/TBC5MAN-Bug-Tracker#40]
# Decription: #
Arcane Missiles dont proc the talent "Clear casting"  
# How it works: #
Arcane missiles cant proc a clear casting (Arcane Talent tree)
# How it should work: #
On every arcane missiles damage tick should be a 2/4/6/8/10 % (depends how much points you put into the talent)  chance to proc the clear casting.
# Source - You need to provide a source as evidence: #
Just read talent: Give you a 10 % chance of entering a Clearcasting state after ANY damage spell hits a target.
# Additional Information: #

**Comment by Yatzii93** [comment]
Invalid - https://us.forums.blizzard.com/en/wow/t/arcane-missiles-and-clear-casting-arcane-concentration-bug/302706/17

As far as I can see this is bugged private server interaction and it's not an offical thing at all. If this in incorrect please assist with providing valid evidence for this claim.
