### ISSUE TITLE
[ROGUE] Cheat Death not procing somtimes 🐛 [Bug Report]

### ISSUE THREAD

**Issue by wowas9090** [Yatzii93/TBC5MAN-Bug-Tracker#41]
# Decription: Cheat Death is not working. If you que arena and if it is activated during fight and u finish arena Cheat Death won't proc once again. We tried relog / respec but still buged.

# How it works: #
Cheat Death should proc again after one minute, but it never procs again.
# How it should work: #

You have a 100% chance that an attack which would otherwise kill you will instead reduce to 10% of your maximum health. In addition, all damage will be reduced by up to 90% for 3 seconds. This effect can not occur more that once per minute

# Source - You need to provide a source as evidence: #
https://www.wowhead.com/spell=31231/cheat-death
# Additional Information: #
It is reproducible.

**Comment by Yatzii93** [comment]
Tested and I am unable to reproduce this. It procced again after the 1 min cooldown.
