### ISSUE TITLE
🐛 [Shaman] - Totem LoS issue

### ISSUE THREAD

**Issue by Holycoke** [Yatzii93/TBC5MAN-Bug-Tracker#44]
# Decription: #
Totem are place able auras and should ignore LoS 
Mana spring, strength of earth, grace of air and wrath of air is already working this way.
totems that dont apply a buff however seems to be missing. 

# How it works: #
Totems like:
Windfury totem - spell=25582
--Poison cleansing totem - spell=8167
Tremor totem  - spell=8145
Mana tide totem - spell=16191
grounding totem - spell=8179  ---SEE ADDITIONAL INFORMATION---
Are following the rules of targeted spells for LoS and not auras

(you cant get the effects of the totems listed here, while not being in line of sight of them)

# How it should work: #
The totems above should follow the same rules for applying its effect as the other buff totems/auras in the game.

You should not need to be in line of sight of your x- totem(any totem) to get its effect 

# Source - You need to provide a source as evidence: #

poison cleaning totem 
https://www.youtube.com/watch?v=9MKE0uN9_6c
3.41 PoV shaman gets a 2. application of the hunter pets poision.
3.42 PoV shaman gets one of the applications cleansed by his totem, while out off LoS

# Additional Information: #
could use more evidence.
im unsure if totems like earthbind totem (spell=6474) should follow the same rules as the buff totems. so i left out (offensive) totems from this report. 

--- As for grounding totem--
The totem only works if enemy caster is with in line of sight of the totem. 
even if the shaman is in Line of sight the spell will not be grounded.

**Comment by Cynovski** [comment]
To add the current behavior of totems on tbc5man, I did a little youtube video to show how it works. 

https://www.youtube.com/watch?v=1XXPDOZ_zoI&feature=youtu.be

Tested with **Windfury**, **earthbind** (not found any proof that it should also work when not in LoS tho)  and **tremor** totems but more shouldn't work as Holycoke said.

**Comment by ziokisame** [comment]
Yes, its a gamebreaking bug, expecially in arena or pvp situations for shamans. 

Basically totems that will give an aura, or a beneficial buffs are supposed to work EVEN behind pillars. This is true for Tremor totem, Mana spring, Healing stream, strength and agi totem, resistances totems, poison and disease cleansing, grounding totem.

Offensive totems, like Magma totem, earthbind, searing totem, ARE NOT supposed to affect enemies behind pillars.

These are just examples, but this is the rule.

12 years of pvping as shaman is my proof xD

**Comment by oldspices** [comment]
can confirm not having grounding / mana tide working thru LOS seriously gimps shamans in arena :(

**Comment by Yatzii93** [comment]
I'm going to try find some more info on this but ye offical confirmation or something or sorts is what I'm looking for.

**Comment by Yatzii93** [comment]
![image](https://user-images.githubusercontent.com/47720837/84509246-526da280-acbb-11ea-9cdd-5e004245913d.png)
Closing, will reopen if official confirmation prove changes were uneccesscary or it needs a revisit.
