### ISSUE TITLE
🐛 [Bug Report] - Felstalker Set Bonus not providing 20 Hit

### ISSUE THREAD

**Issue by Seraaz** [Yatzii93/TBC5MAN-Bug-Tracker#45]
# Decription: #
The Leatherworking BoE crafted Felstalker Set does not provide the 20 Hit rating set bonus even when character has 350 LW.
# How it works: #
Set bonus is not active and does not provide 20 Hit rating.
# How it should work: #
It should provide 20 Hit rating when full set is worn and LW is at least 350.
# Source - You need to provide a source as evidence: #
Own testing. 
![+](https://user-images.githubusercontent.com/61938479/76163995-3d78f480-614b-11ea-8e54-714b7e4e9965.jpg)
![-](https://user-images.githubusercontent.com/61938479/76163996-42d63f00-614b-11ea-98b2-763a15ffc78e.jpg)
![lw](https://user-images.githubusercontent.com/61938479/76163999-4669c600-614b-11ea-8fc5-90543024a300.jpg)

# Additional Information: #

**Comment by Yatzii93** [comment]
Tested and working fine. Closing.
