### ISSUE TITLE
🐛 [Priest] - Eye of Gruul 

### ISSUE THREAD

**Issue by Sity-troll** [Yatzii93/TBC5MAN-Bug-Tracker#46]
# Description: #
Once the trinket procs it should reduce the mana cost of your next heal cast within 15 minutes. This trinket currently only works with Renew
# How it works: #
Every heal can proc the trinket but only renew can use the proc as you can see
![Capture](https://user-images.githubusercontent.com/62414339/77137587-cdce0800-6a6e-11ea-9507-5907edcbff06.PNG)
![Capture2](https://user-images.githubusercontent.com/62414339/77137590-d1fa2580-6a6e-11ea-8942-49ccd51dc0f8.PNG)
![capture3](https://user-images.githubusercontent.com/62414339/77137703-45039c00-6a6f-11ea-8099-f2ad71f9d0ac.PNG)
(forgot to take a screenshot of CoH but can't use the proc either)
# How it should work: #
When the trinket procs it should reduce the mana cost of ANY next healing spell not just renew.

# Source - You need to provide a source as evidence: #
https://www.wowhead.com/item=28823/eye-of-gruul#comments

# Additional Information: #
https://tbcdb.com/?item=28823
https://tbcdb.com/?spell=37705

https://tbcdb.com/?spell=25235
https://tbcdb.com/?spell=34119
https://tbcdb.com/?spell=33076
https://tbcdb.com/?spell=25308
https://tbcdb.com/?spell=34866
https://tbcdb.com/?spell=32546
https://tbcdb.com/?spell=25222

**Comment by Yatzii93** [comment]
Invalid working as expected.

![image](https://user-images.githubusercontent.com/47720837/77173002-c599bb00-6ab6-11ea-9aea-a702c8db94d3.png)

**Comment by Sity-troll** [comment]
Sorry I wasn't clear. Every heal can proc the trinket but the buff it gives only works with renew at the moment.

**Comment by Yatzii93** [comment]
AH I will reinvestigate
