### ISSUE TITLE
[Magister's Terrace - Kael'thas Sunstrider] - Gravity Lapse Spell Timing

### ISSUE THREAD

**Issue by Redeyed03** [Yatzii93/TBC5MAN-Bug-Tracker#48]
The last two times I've done Magister's terrace, once heroic and once normal, the gravity lapse spell has not casted on players during the transition. Players are then forced to run around on the ground to avoid the arcane energy balls. On the normal version we were able to kill him pretty fast but on the heroic version he casted gravity lapse on us toward the end of the fight(Kael was less than 10ish percent).

**Comment by Yatzii93** [comment]
I'll investigate this tonight/tomorrow morning. Should be an easy fix.

**Comment by Yatzii93** [comment]
This should be fixed now, please reopen if it happens again.
