### ISSUE TITLE
🐛 [Bug Report] - Cristal Spire of Karabor

### ISSUE THREAD

**Issue by ThomLlobEce** [Yatzii93/TBC5MAN-Bug-Tracker#5]
# Decription: #
The effect of the mace isn't working well.

# How it works: #
If the target is below 25% HP, direct healing spells cause target to be healed for an additional 180 to 220 health.

# How it should work: #
If the target is below 50% HP, direct healing spells cause target to be healed for an additional 180 to 220 health.

It means that if target is below 50% but above 25% it won't get the bonus heal whereas it should.

# Source - You need to provide a source as evidence: #
The tooltip of the weapon.
https://youtu.be/yzn1aLXzD7I

# Additional Information: #

**Comment by Yatzii93** [comment]
Its bugged but not in the way you are describing. It's factoring in the persons hp after the heal rather than before.
