### ISSUE TITLE
🐛 [Bug Report] - [BT] Door before Shahraz closes after porting up with 3 players

### ISSUE THREAD

**Issue by Noaphiel** [Yatzii93/TBC5MAN-Bug-Tracker#61]
# Decription: #
There is a rare scenario, where the door before Mother Shahraz closes instead of opening, when 3 people porting up with the quest.

# How it works: #
Reproduction steps:
1. Kill Supremus -> this unlocks the door.
2. Reset the instance by staying out for 5 minutes or continuing on the next day
3. If you continue on that ID and you use 3 people taking the questbased teleporter (kill illidan 2 times) the door closes, even though it was open before. The only possible way to get this door opened again is to reset the instance and port up with the normal port that appears after killing akama.

# How it should work: #
The door should stay open.

# Source - You need to provide a source as evidence: #
well, can't provide any sources, since how would it help to take a screenshot in front of a closed door ;).

# Additional Information: #
The scenario written above occured on my BT run, where we were continuing someones save. The door was opened due to Supremus  being dead (one guy went past the door to look, whether mother is still alive) and after we used the quest teleporter with three people the door closed. Occured on may 1st at around 9 am server time with following players: Ukagii, Elmagonorrea, Andriena, Noaphiel, Bananakush.
Noaphiel, Elmagonorrea and Bananakush used the teleporter.

**Comment by Yatzii93** [comment]
but why not do the normal teleport instead

**Comment by Noaphiel** [comment]
imo, it's a habit to use the right one. Usually you just run token bosses without Akama being dead, where only the right one is available. If we were aware of that behaviour I'd have totally used the other teleporter.
