### ISSUE TITLE
🐛 [Bug Report] - horde Warbringer

### ISSUE THREAD

**Issue by alfha999** [Yatzii93/TBC5MAN-Bug-Tracker#64]
# Decription: Horde Warbringer does not correctly offer Daily PVP quests for horde players.

# How it works: When speaking to him all he offers is “For Great Honor”, but the daily pvp quest “Call to Arms: xxxxxxxxx” is unavailable. 

# How it should work: He should be offering both quests to players just like how the alliance Brigadier General functions currently offering “Concerted Efforts” and the daily “Call to Arms: xxxxxxxxx”.

# Source - You need to provide a source as evidence: what kind of source? My source is playing ingame? Please let me know if more info/proof is needed. 

# Additional Information: n/a

**Comment by Yatzii93** [comment]
Working fine when tested. It this more likely a Cache issue on your end.

**Comment by alfha999** [comment]
Cache clear fixed! Thank you!
