### ISSUE TITLE
🐛 [Bug Report] - Naaru Ration & Conjured Mana Biscuit incorrect food type

### ISSUE THREAD

**Issue by alfha999** [Yatzii93/TBC5MAN-Bug-Tracker#65]
# Decription: # Naaru Ration & Conjured Mana Biscuit incorrect food type, was originally recognized as bread in retail. 

# How it works: # Naaru Ration & Conjured Mana Biscuit are unrecognized and return an error when trying to feed to a Wind Serpent pet. 

# How it should work: # There should be no errors returned and the feed pet spell should allow these items to be fed. 

# Source - You need to provide a source as evidence: https://vanilla-wow.fandom.com/wiki/Feed_Pet

“ Pets that eat bread can eat food conjured by mages.”

Having difficulty finding proof of naaru ration food type. Best I can find is in the change log of this tbc add-on. 

https://wowinterface.com/downloads/info4160-FizzwidgetFeed-O-Matic.html#changelog

3.0.3 changes
“ - Fixes subcategory/supercategory linkage issues that caused FOM to ignore certain foods (such as Conjured Mana Biscuit and Naaru Ration).”

Here is another post 

http://fizzwidget.com/gfw-feedomatic-2-4-1/

Metooz Says: 
April 19th, 2008 at 5:53 pm
NVM the above comment. All you have to do is type /fom add (diet) (item link) then you can use the naaru ration or whatever else. You can find more info in the readme that comes w/ the addon. The diet type for manna biscuits and naaru rations is Bread so u would type /fom add bread [Naaru Ration] with that last part being the linked item. Hope this helps

# Additional Information: #

**Comment by Yatzii93** [comment]
Only certain pet types can eat the mana buiscuits and it's working as intended. This is invalid.

**Comment by alfha999** [comment]
Yes, my pet is the wind serpent, which should be able to eat bread.

**Comment by alfha999** [comment]
Oh you're right its working now. But the Naaru ration is still incorrect.
