### ISSUE TITLE
🐛 [Bug Report] - Storming Wind Ripper immunity

### ISSUE THREAD

**Issue by alfha999** [Yatzii93/TBC5MAN-Bug-Tracker#66]
Not a huge issue but I thought I would put it here. 

# Decription: Storming Wind Rippers on the elemental plateau are immune to arcane effects and damage. 

# How it works: This was discovered when attacking said mob they are immune to arcane shot damage and to the hunters mark spell. 

# How it should work: Hunters mark should apply and arcane shot should damage said mob. 

# Source - You need to provide a source as evidence: Source is from in-game. 

# Additional Information: #

**Comment by alfha999** [comment]
![Uploading Screen Shot 2020-05-07 at 10.15.29 PM.png…]()

**Comment by alfha999** [comment]
Might not be arcane damage but thats what it seemed like. heres a screenshot. didnt mean to close it :X

**Comment by Yatzii93** [comment]
Need proof that they arent immune to arcane damage.

**Comment by Yatzii93** [comment]
https://github.com/Looking4Group/L4G_Core/issues/3332

Closing until sufficient proof is provided. Just because it's frustrating doesnt not mean it constitutes a bug, ofc unless proven otherwise.

**Comment by alfha999** [comment]
Might not be arcane damage, but it shouldn't be immune to arcane shot or hunters mark.
