### ISSUE TITLE
🐛 [Bug Report] - Hunter pet buffs bug

### ISSUE THREAD

**Issue by alfha999** [Yatzii93/TBC5MAN-Bug-Tracker#69]
# Decription: # Hunter pets lose buffs whenever zoning or teleporting into a new zone.

# How it works: Hunter pets will have buffs normally but once you zone into or teleport into a new zone your pet loses all Paladin buffs besides might and loses all world buffs as well. 

# How it should work: All buffs on pet should remain regardless of zone change. 

# Source - You need to provide a source as evidence: In game normal play. 

# Additional Information: #

**Comment by Yatzii93** [comment]
The pala buffs are coming from the custom raid buff bots and as such they are subjected to stacking rules on new zone entry for players and pets. So this is a intended result and wont be fixed.

**Comment by alfha999** [comment]
What about world buffs?

**Comment by alfha999** [comment]
Really though what’s the point of hunters pets getting all the buffs at the naaru in at the entrance only for them to disappear if you take the teleport to kalecgos or the portal up to sapphiron ? So hunters must walk all the way if they want 33% of their dps to still have buffs? :(
