### ISSUE TITLE
🐛 [Bug Report] - Elemental Mastery

### ISSUE THREAD

**Issue by Lockersky** [Yatzii93/TBC5MAN-Bug-Tracker#7]
# Decription: #
Shaman elemental can't use ELEMENTAL MASTERY short after cast, becouse dmg incoming use stack.
# How it works: #
When shaman elemental cast Elemental Mastery short after spell like LB or CL, then Elemental Mastery "get out". I mean Elemental Mastery fade with dmg, not with casted spell.
# How it should work: #
Elemental Mastery should pop up with next spell, NOT WITH NEXT DMG. I mean if we do LB-EM-LB. elemental mastery should get out with next casted spell.
# Source - You need to provide a source as evidence: #
description of spell...
https://vanilla-twinhead.twinstar.cz/?spell=16166
# Additional Information: #

**Comment by Lockersky** [comment]
btw sorry about that english, but imo i wrote it with style to understand it XD

**Comment by Lockersky** [comment]
> to clarify: the EM buff will be consumed by the cast that is already travelling, so you wont have a 100% guaranteed crit if you dont wait for the travelling spell to hit first or the buff will be consumed regardless.

thats what im talking about. EM should be consumed after CAST, not after DMG ;/

**Comment by Yatzii93** [comment]
Yep aware of this bug. It's been investigate quite a lot and it's apart of a larger issue with proc system. It really needs a rework or overhaul at some point to truly tackle this issue. It's the same with the flurry bug from another ticket.
