### ISSUE TITLE
🐛 [Bug Report] - Hunter pets losing world buffs. 

### ISSUE THREAD

**Issue by alfha999** [Yatzii93/TBC5MAN-Bug-Tracker#71]
Decription: # Hunter pets lose world buffs whenever zoning or teleporting into a new zone.

How it works: Hunter pets will visibly have world buffs but once you zone into or teleport into a new zone all world buffs are lost. 

How it should work: All buffs on pet should remain regardless of zone change.

Source - You need to provide a source as evidence: Weren’t changes made to include pets in world buffs originally? I remember them not being applied to pets and then a change being made to allow them, but now they don’t persist though? :/

Additional Information: Please allow hunter pets the buffs as they are 33% of BM hunters dps!

**Comment by Yatzii93** [comment]
Hunter pets arent even included in the world buffs so Im not sure why this is being brought up as a bug?
