### ISSUE TITLE
🐛 [Bug Report] - Nuromac is not tamable

### ISSUE THREAD

**Issue by Salvoita** [Yatzii93/TBC5MAN-Bug-Tracker#74]
# Decription: #
Nuromac npc is not tamable

# How it works: #

# How it should work: #
This npc is rare pet tamable
# Source - You need to provide a source as evidence: #

# Additional Information: #
I sent a video to yatzi in discord

**Comment by Yatzii93** [comment]
![image](https://user-images.githubusercontent.com/47720837/82047029-f9095800-96a9-11ea-9ca3-f64efa322e52.png)
