### ISSUE TITLE
🐛 [Bug Report] - Hunter Traps should not overlap

### ISSUE THREAD

**Issue by chuupaaa** [Yatzii93/TBC5MAN-Bug-Tracker#75]
# Decription: #
At the moment it is possible to have an ice trap and some other trap. For example - it is possible to have 2 ice traps (white slow stuff on the ground) so you can kite mobs or players (specially in pvp) super easy, because they cover twice the ground. It is also possible to have the same slow trap active (and slowing people) and then in addition, place a frost trap.

# How it works: #
One hunter can have 2 traps active at the same time.

# How it should work: #
One hunter can only have 1 active trap at the time.

# Source - You need to provide a source as evidence: #
![HunterTraps](https://user-images.githubusercontent.com/65570132/82262922-1f591d00-9962-11ea-9d7b-0212b8ec4ea7.png)

# Additional Information: #

**Comment by Yatzii93** [comment]
Prove that this isn't possible in TBC because if the traps off cooldown I don't see why you couldn't have another up for a small period if the spell duration is longer than the trap cooldown.

**Comment by chuupaaa** [comment]
fair enough, I'll update if I find something.

**Comment by Yatzii93** [comment]
Closed in the meantime.
