### ISSUE TITLE
🐛 [Bug Report] - Priest using mind control disables disc talents (and possibly other specs too)

### ISSUE THREAD

**Issue by oldspices** [Yatzii93/TBC5MAN-Bug-Tracker#78]
# Decription: #
If you mind controll someone, It removes your talents from working, no more martydom procs, etc, and mass dispell takes 1.5 sec instead of .5- it makes it so your special talents ddont work until you relog.
# How it works: #

# How it should work: #
should not disable 
# Source - You need to provide a source as evidence: #
very easy to test and prove, idk  how to easily upload video. 
# Additional Information: #
PS Pain suppression also always has 0% chance to resist dispell when it says its 65 static+20% if talented. resist chance.

**Comment by ziokisame** [comment]
It disables ALL the talents. Shadow, holy, disc. Basically it's like playing with no talents, you keep you abilities on use, like pain suppression, shadow form, vampiric touch etc, but some of them gets even nerfed, like pain suppression dispel mechanic resistance. 
Unfortunately it almost kills priest in arena, considering that mind control is a core spell expecially in 2v2

**Comment by Yatzii93** [comment]
Fixed.
