### ISSUE TITLE
🐛 [Bug Report] - Mana Fiend Health not scaling with gear

### ISSUE THREAD

**Issue by oldspices** [Yatzii93/TBC5MAN-Bug-Tracker#81]
# Decription: #
Mana fiend Health (probably damage too?) Not scaling with gear- Resulting in it getting 1 shot in pvp.  (poses risk in pve too i assume)
# How it works: #
![manafiend](https://user-images.githubusercontent.com/26885524/83406524-4a5c5b80-a3bb-11ea-9e68-b17268792abd.png)
I tested full gear pvp vs starter priest both had same HP (~2k) 
# How it should work: #
Bc icon Patch 2.1.2 (2007-06-19): This creature will now reset to full health when it is summoned. It will also automatically attack your current enemy target when it is summoned.
Bc icon Patch 2.1.0 (22-May-2007): This pet will now come into the game with full health and mana, including that gained from a percentage of its master’s stamina and intellect.; The Shadowfiend will now correctly attack your target even if it is neutral or non-aggressive.; Increased the Shadowfiend’s chance to hit higher level enemies
# Source - You need to provide a source as evidence: #
https://wowwiki.fandom.com/wiki/Shadowfiend
# Additional Information: #
when testing i noticed it behaved a little diff vs target dummy and in duels

druids get innervate, shamans get mana tide(even tho its not working if u LOS it), pala get divine illumination  to boost the problem of going oom in arena and yet priests get fucked in that department :)

**Comment by Yatzii93** [comment]
The shadowfiend mana bonus is boosted by the players shadows damage and it is working correctly. I'm not really sure what you are refering to when you are saying priests get fucked. There are no custom changes being applied to pvp so if you think they are getting fucked, then you need to accept it. It's how it was back in retail. Also it's hp is scaling with gear.

**Comment by oldspices** [comment]
@Yatzii93  its showing it with 2400hp out of 5k - and in the patch note you can see its supposeedto spawn with full hp . so its dieing in 1 hit, and only granting~100 mana per hit in pvp. in raidss it grants~500 mana per hit.

**Comment by Yatzii93** [comment]
ye it's a custom change that only applies to raids. Otherwise it's retail calculations.
![image](https://user-images.githubusercontent.com/47720837/83594767-fc308f00-a557-11ea-9650-ce9e1120a0b4.png)

**Comment by Yatzii93** [comment]
actually just tested #81 [Bug Report] - Mana Fiend Health not scaling with gear
- Its actually working, there is no bug with missing health scarling, it should use the players stamina and interlect and it does that currently.  No buffs 41xx , with buff on player ( not on fiend ) 47xx.
Also the Description is wrong. The Priest pet is called "Shadowfiend" and Manafiend is a lvl 60 elite npc in AQ 20 ^^ - Kassierer
