### ISSUE TITLE
🐛 [Bug Report] - Absorb/shield effects Not stopping flag captures/CC effects/stealth

### ISSUE THREAD

**Issue by oldspices** [Yatzii93/TBC5MAN-Bug-Tracker#82]
# Decription: #
Absorb/shield effects Not stopping flag captures/CC effects  such as capturing a base in AB/flag in EOTS and Sap/poly/Blind/fear/etc as well as stealth
# How it works: #
any effect that absorbs damage (pw:s, ice armor, mana shield, sacrafice, blacksmithing runes, etc) will prevent interruption on flags / cc
# How it should work: #

# Source - You need to provide a source as evidence: #
still scowering for old videos on youtube as proof but this should  be a given.
# Additional Information: #

**Comment by oldspices** [comment]
@Yatzii93  is it information, or proof you need, not sure how to go forward here

**Comment by Exeasd** [comment]
[https://youtu.be/ZYb5SVo4dz0?t=76](https://youtu.be/ZYb5SVo4dz0?t=76)  He absorbed smth while having pws on himself and the flag capturing instantly stopped
