### ISSUE TITLE
🐛 [Bug Report] - Shaman talent Focused Mind bugged

### ISSUE THREAD

**Issue by oldspices** [Yatzii93/TBC5MAN-Bug-Tracker#85]
# Decription: #
restotree talent- focused mind, reduces duration of any silence or interrupt effect by 30%
# How it works: #
if you get interrupted it is fullduration.  silence seems to work tho.
# How it should work: #
it should be 30% less
# Source - You need to provide a source as evidence: #
Just have a mage counter spell you , it is full 8 seconds.
# Additional Information: #

**Comment by Yatzii93** [comment]
Combined.
