### ISSUE TITLE
🐛 [Bug Report] - shaman totem despawn if you place it as the other one fades or is killed

### ISSUE THREAD

**Issue by oldspices** [Yatzii93/TBC5MAN-Bug-Tracker#87]
# Decription: #
its kinda odd but i noticed if you drop a totem right as the other one from the same element(fire,air,water,earth) class fades or is destroyed, the new one is also destroyed- it has to be at basically the same exact time. 
# How it works: #
I dropped a mana tide right as mana spring faded and mana tide got deleted instantly- ive also had this happen when people kill the totems in pvp 20 yards away, the totem i drop neearby gets "killed" from that action 20 yards away.  (i am 100% sure nothing else killed the new totems)
# How it should work: #
should be ableee to replace totems without risk of it despawning instantly. 
# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by Yatzii93** [comment]
Cant reproduce closing for now.
