### ISSUE TITLE
🐛 [Bug Report] - Tauren transmog for xfaction bg's get stuck inside beserker hut's

### ISSUE THREAD

**Issue by oldspices** [Yatzii93/TBC5MAN-Bug-Tracker#88]
# Decription: #
if you areturned into a tauren you are too big to get out of the building at farm (AB ) And the alliance beserker hut in WSG- moving fast out does notwork- I think you maybe get stuck if youare an actual tauren too? but if you movefast youcanget out, where as if your transmog youre stuck. 
# How it works: #

# How it should work: #

# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by Yatzii93** [comment]
The thing is the spell model scaling and the models are all determined by the client. Spell is pulled from the client and the models are from the client. Odd.

**Comment by jazzybar** [comment]
Happened to me while being Tauren (female) myself, in Arathi Bassin at the Farm. I had to remove the berserker buff to get out, tried also in cat / bear / unmorphed but nothing worked.
