### ISSUE TITLE
🐛 [Bug Report] - Boats travel

### ISSUE THREAD

**Issue by BlackNemesi** [Yatzii93/TBC5MAN-Bug-Tracker#9]
I noticed a problem with the boats, when I take a boat, as soon as I set foot on the pier it teleports me to a completely different area, it happened to me twice, the first one brought me back to the dock where I started from, the second one starting from booty bay , I'm going to set foot on the ratchet pier and teleport me to arathi highlands in the sky and fall down dying there.

**Comment by Yatzii93** [comment]
Its the anti-cheat system I probably need to retweak it.
