### ISSUE TITLE
🐛 [Bug Report] - [rogue] mutilate and seal fate

### ISSUE THREAD

**Issue by Keuk-Cho-Hon** [Yatzii93/TBC5MAN-Bug-Tracker#90]
# Decription: #
Mutilate and Seal Fate are currently not interacting correctly
# How it works: #
Sometimes mutilate does not get a bonus combo point even though one of the hits has crit.
# How it should work: #
Any time either hand crits in a mutilate, an extra combo point should be awarded.
# Source - You need to provide a source as evidence: #
![image](https://user-images.githubusercontent.com/66455353/83896612-6d23a280-a722-11ea-9e42-feef11077dea.png)
went and smacked a target dummy a few times to show what I mean. as you can see, the big 473 is a critical hit, but there are only two combo points on the dummy.

# Additional Information: #
I believe it is off hand crits that are not triggering seal fate. I don't know for sure as I was noticing this during live play.

**Comment by Yatzii93** [comment]
The offhand damage is a generic melee hit. If you look at the talent it states it has to come from a spell that generates a combo points. Closing.
