### ISSUE TITLE
🐛 [Bug Report] - [auchenai crypts] mind control not dispelling

### ISSUE THREAD

**Issue by Keuk-Cho-Hon** [Yatzii93/TBC5MAN-Bug-Tracker#91]
# Decription: #
some mobs mind control and it does not dispel when it should
# How it works: #
when you get mind controlled you either have to sit out the entire 30 second duration or get killed and resurrected.
# How it should work: #
according to the tool tip, the MC should break when you drop below 50% HP.
# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by Yatzii93** [comment]
- no bug. The mindcontrol lasts 1 minute ( thats normal and listed on wowhead) 
https://www.wowhead.com/tbc/spell=32830/possess as listed. No dispel type, unaffected by school immunity. Just kill the 3,x k hp mob within 5s and you are fine...
