### ISSUE TITLE
🐛 [Sunwell Plateau] - M'uru no phase 2

### ISSUE THREAD

**Issue by schanzee** [Yatzii93/TBC5MAN-Bug-Tracker#92]
# Decription: #
We killed M'uru yesterday and the transition to Entropius didn't finish.
# How it works: #
We brought M'uru to 0 Hp and i think the transition started (all the portals opened around him) we killed all the remaining adds but eventually dropped combat and the transition didn't finish. M'uru was still floating in the room but "Dead". 
I've seen this reported somewhere on discord I think but can't find it now. We killed all the adds but I felt like the transition lasted pretty long so im not sure if the transition stopped because we killed all the adds and there was nothing to keep us in combat or we eventually killed all the adds because the transition didn't happen. 
# How it should work: #

# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by schanzee** [comment]
https://discordapp.com/channels/379643684922327051/651591463121059851/718224987730870372 found it

**Comment by Yatzii93** [comment]
![image](https://user-images.githubusercontent.com/47720837/84995705-3d25c780-b144-11ea-85c8-d97e8ed5b065.png)
Wil reopen if it reoccurs.
