### ISSUE TITLE
🐛 [Bug Report] - Quest for Alliance called "Disrupt their Reinforcements"

### ISSUE THREAD

**Issue by alfha999** [Yatzii93/TBC5MAN-Bug-Tracker#93]
# Decription: The Hellfire quest for Alliance called "Disrupt their Reinforcements" is bugged, preventing players from completing the rest of the quest chain, which is worth a lot of rep.

# How it works: When you go to blow up Portal Grimh or Kaalez after completing channeling it returns with a error saying invalid target.

# How it should work: You should be able to click the gate with required quest items and complete the quest requirements

# Source - You need to provide a source as evidence: In 
![Screen Shot 2020-06-16 at 1 13 20 PM](https://user-images.githubusercontent.com/54584697/84823662-928e9700-afd3-11ea-9e87-0026749fcdb3.png)
![Screen Shot 2020-06-16 at 1 13 14 PM](https://user-images.githubusercontent.com/54584697/84823664-94f0f100-afd3-11ea-927c-60d625ba67db.png)

game play.

# Additional Information: #

**Comment by Yatzii93** [comment]
Works fine if you move in closer.
