### ISSUE TITLE
🐛 [Bug Report] - Zul'Aman: Rarely eggs without a hatcher will hatch 

### ISSUE THREAD

**Issue by Hominghead** [Yatzii93/TBC5MAN-Bug-Tracker#97]
# Decription: #
Dragonhawk add releasing is not working correctly.

# How it works: #
Killing one of the hatchers, he will eventually release 2 extra Dragonhawks anyway

# How it should work: #
Dead hatchers should not release any Dragonhawks on that side

# Source - You need to provide a source as evidence: #
https://www.youtube.com/watch?v=vdW8KPP28vw

**Comment by Yatzii93** [comment]
I'm looking at it now, it's happens on occasion but it isn't associated with the dead hatcher. I think it's a spell radius issue where the other egg hatching spell is clipping the objects in some cases

**Comment by Yatzii93** [comment]
Also fixed issue with hatcher spawning eggs rapidly if he switches sides.
