### ISSUE TITLE
🐛 [Bug Report] - Arcane Missile does not proc clear casting

### ISSUE THREAD

**Issue by Slimmjimmm** [Yatzii93/TBC5MAN-Bug-Tracker#98]
# Decription: # Arcane Missile does not proc clear casting

# How it works: # You can cast arcane missile but it never procs clear casting

# How it should work: # Arcane missile should be able to proc clear casting on the initial cast

# Source - You need to provide a source as evidence: # https://wowwiki.fandom.com/wiki/Arcane_Concentration?oldid=1432055

# Additional Information: #

**Comment by Yatzii93** [comment]
Arcane Missiles never procced clear casting in TBC or Vanilla.
