### ISSUE TITLE
🐛 [Bug Report] - Halazzi has some weird aggro-range behaviour

### ISSUE THREAD

**Issue by Hominghead** [Yatzii93/TBC5MAN-Bug-Tracker#99]
# Decription: #
Shaman placed some totems and it made Halazzi trigger his OnPull and then leave combat again repeatedly

# How it works: #
Not entirely certain, but looks like you have to hit some sweet spot on the aggro-range and then it will cause this weird behaviour? (Or maybe there is something else...)

# How it should work: #
Halazzi should either get pulled or not get pulled, not wobble in-between

# Source - You need to provide a source as evidence: #
https://www.youtube.com/watch?v=_dBAm9nLjjo

# Additional Information: #
how ya like that huh?

**Comment by Yatzii93** [comment]
It's related to the code that stops people using pets to pull the boss through doors. I'll modify it to not apply to totems. Good catch.

**Comment by Yatzii93** [comment]
Next time you'll have a dead Shaman :)

**Comment by Hominghead** [comment]
Nice :D
